version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    env_file:
      - ./backend/.env
    volumes:
      - ./data/vectorstore:/app/vectorstore
      - ./data/cache:/app/cache
      - ./data/logs:/app/logs
      - ./data/uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: chaxai
      POSTGRES_USER: chaxai
      POSTGRES_PASSWORD: chaxai123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:
    name: chaxai-network